# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\pylearm\GUI\pyQt5\ForgeCreator\src\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 606)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 24))
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        self.File.setObjectName("File")
        self.Edit = QtWidgets.QMenu(self.menubar)
        self.Edit.setObjectName("Edit")
        self.Create = QtWidgets.QMenu(self.Edit)
        self.Create.setObjectName("Create")
        self.Help = QtWidgets.QMenu(self.menubar)
        self.Help.setObjectName("Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.New = QtWidgets.QAction(MainWindow)
        self.New.setObjectName("New")
        self.Block = QtWidgets.QAction(MainWindow)
        self.Block.setObjectName("Block")
        self.Item = QtWidgets.QAction(MainWindow)
        self.Item.setObjectName("Item")
        self.Tag = QtWidgets.QAction(MainWindow)
        self.Tag.setObjectName("Tag")
        self.Sound = QtWidgets.QAction(MainWindow)
        self.Sound.setObjectName("Sound")
        self.Command = QtWidgets.QAction(MainWindow)
        self.Command.setObjectName("Command")
        self.Recipe = QtWidgets.QAction(MainWindow)
        self.Recipe.setObjectName("Recipe")
        self.aHelp = QtWidgets.QAction(MainWindow)
        self.aHelp.setObjectName("aHelp")
        self.About = QtWidgets.QAction(MainWindow)
        self.About.setObjectName("About")
        self.File.addAction(self.New)
        self.Create.addAction(self.Block)
        self.Create.addAction(self.Item)
        self.Create.addAction(self.Tag)
        self.Create.addAction(self.Sound)
        self.Create.addAction(self.Command)
        self.Create.addAction(self.Recipe)
        self.Edit.addAction(self.Create.menuAction())
        self.Help.addAction(self.aHelp)
        self.Help.addAction(self.About)
        self.menubar.addAction(self.File.menuAction())
        self.menubar.addAction(self.Edit.menuAction())
        self.menubar.addAction(self.Help.menuAction())

        self.retranslateUi(MainWindow)
        self.menubar.triggered['QAction*'].connect(MainWindow.createNew) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forge模组构建器"))
        self.File.setTitle(_translate("MainWindow", "文件"))
        self.Edit.setTitle(_translate("MainWindow", "编辑"))
        self.Create.setTitle(_translate("MainWindow", "创建..."))
        self.Help.setTitle(_translate("MainWindow", "帮助"))
        self.New.setText(_translate("MainWindow", "新建"))
        self.Block.setText(_translate("MainWindow", "方块"))
        self.Item.setText(_translate("MainWindow", "物品"))
        self.Tag.setText(_translate("MainWindow", "标签"))
        self.Sound.setText(_translate("MainWindow", "音效"))
        self.Command.setText(_translate("MainWindow", "命令"))
        self.Recipe.setText(_translate("MainWindow", "配方"))
        self.aHelp.setText(_translate("MainWindow", "帮助..."))
        self.About.setText(_translate("MainWindow", "关于..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())